# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bootfrog/PhotoMosaic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bootfrog/PhotoMosaic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bootfrog/PhotoMosaic/CMakeFiles /home/bootfrog/PhotoMosaic/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bootfrog/PhotoMosaic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Preprocess

# Build rule for target.
Preprocess: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Preprocess
.PHONY : Preprocess

# fast build rule for target.
Preprocess/fast:
	$(MAKE) -f CMakeFiles/Preprocess.dir/build.make CMakeFiles/Preprocess.dir/build
.PHONY : Preprocess/fast

#=============================================================================
# Target rules for targets named PhotoMosaic

# Build rule for target.
PhotoMosaic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PhotoMosaic
.PHONY : PhotoMosaic

# fast build rule for target.
PhotoMosaic/fast:
	$(MAKE) -f CMakeFiles/PhotoMosaic.dir/build.make CMakeFiles/PhotoMosaic.dir/build
.PHONY : PhotoMosaic/fast

PhotoMosaic.o: PhotoMosaic.cpp.o

.PHONY : PhotoMosaic.o

# target to build an object file
PhotoMosaic.cpp.o:
	$(MAKE) -f CMakeFiles/PhotoMosaic.dir/build.make CMakeFiles/PhotoMosaic.dir/PhotoMosaic.cpp.o
.PHONY : PhotoMosaic.cpp.o

PhotoMosaic.i: PhotoMosaic.cpp.i

.PHONY : PhotoMosaic.i

# target to preprocess a source file
PhotoMosaic.cpp.i:
	$(MAKE) -f CMakeFiles/PhotoMosaic.dir/build.make CMakeFiles/PhotoMosaic.dir/PhotoMosaic.cpp.i
.PHONY : PhotoMosaic.cpp.i

PhotoMosaic.s: PhotoMosaic.cpp.s

.PHONY : PhotoMosaic.s

# target to generate assembly for a file
PhotoMosaic.cpp.s:
	$(MAKE) -f CMakeFiles/PhotoMosaic.dir/build.make CMakeFiles/PhotoMosaic.dir/PhotoMosaic.cpp.s
.PHONY : PhotoMosaic.cpp.s

Preprocess.o: Preprocess.cpp.o

.PHONY : Preprocess.o

# target to build an object file
Preprocess.cpp.o:
	$(MAKE) -f CMakeFiles/Preprocess.dir/build.make CMakeFiles/Preprocess.dir/Preprocess.cpp.o
.PHONY : Preprocess.cpp.o

Preprocess.i: Preprocess.cpp.i

.PHONY : Preprocess.i

# target to preprocess a source file
Preprocess.cpp.i:
	$(MAKE) -f CMakeFiles/Preprocess.dir/build.make CMakeFiles/Preprocess.dir/Preprocess.cpp.i
.PHONY : Preprocess.cpp.i

Preprocess.s: Preprocess.cpp.s

.PHONY : Preprocess.s

# target to generate assembly for a file
Preprocess.cpp.s:
	$(MAKE) -f CMakeFiles/Preprocess.dir/build.make CMakeFiles/Preprocess.dir/Preprocess.cpp.s
.PHONY : Preprocess.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Preprocess"
	@echo "... PhotoMosaic"
	@echo "... PhotoMosaic.o"
	@echo "... PhotoMosaic.i"
	@echo "... PhotoMosaic.s"
	@echo "... Preprocess.o"
	@echo "... Preprocess.i"
	@echo "... Preprocess.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

